version: '3.7'
services:
  db:
    image: pedidos-database
    ports:
      - "5434:5432"
    expose:
      - "5434"
    build:
      context: db-postgres/
    restart: unless-stopped
  pedidos-api:
    image: pedidos-api
    depends_on:
      - pedidos-database
    ports:
      - "9000:9000"
    expose:
      - "9000"
    tty: false
    restart: unless-stopped
volumes:
  postgres-data: